### ISSUE TITLE
Firebase config details public

### ISSUE THREAD

**Issue by Anand987** [lsanjayl/Event-management#18]
Hey Buddy!! your firebase configuration is public so it can be used by anyone, also it is not  a good practice to store the config details like that, you could have used .env file to store the configuration detail and from there you can fetch those details in the auth service.

It would be better if you would do that!! I hope my point can help you!!

**Comment by lsanjayl** [comment]
Hi!! Anand tqsm for checking out ☺️☺️, I don't know those these thing till now thanks man.
And I have a doubt ,Im using this master branch for deployment will it affect my deployemnt after storing the config details in '.env' files.

**Comment by lsanjayl** [comment]
> Hey Buddy!! your firebase configuration is public so it can be used by anyone, also it is not a good practice to store the config details like that, you could have used .env file to store the configuration detail and from there you can fetch those details in the auth service.
> 
> It would be better if you would do that!! I hope my point can help you!!

>Hi!! Anand tqsm for checking out ☺️☺️, I don't know those these thing till now thanks man.
And I have a doubt ,Im using this master branch for deployment will it affect my deployemnt after storing the config details in '.env' files.

**Comment by Anand987** [comment]
Yes it will affect your deployment too!! but I think that as the repo will update and as .env didn't get update on GitHub you have to manually update .env file in your deployment and the configuration there!

**Comment by lsanjayl** [comment]
Okay bro ,then I'll figure out how to do that thing. Thanks for the reminding dude☺️.

**Comment by Anand987** [comment]
> Okay bro ,then I'll figure out how to do that thing. Thanks for the reminding dude☺️.

Closing the issue as you are goin to work on it then...
